### ISSUE TITLE
"Add data" broken for Page Datafolders with publication flow active

### ISSUE THREAD

**Issue by mawtex** [Orckestra/CMS-Foundation#276]
Issue: You try to add data to a page folder and get an error dialog, log contains exception (see below).

Repro: 
1) On the Data perspective, create a Page Datafolder type where "Has Publishing" is selected
2) Save data type and attach it to some page using "Add Datafolder"
3) On the data folder, add data

Expected: You get a form and can add data
Actual: Error dialog

```
System.ArgumentNullException: Value cannot be null.
Parameter name: entityToken

   at Composite.Verify.ThrowArgumentNullException(String parameterName) in ...\Composite\Verify.cs:line 173
   at Composite.Verify.ArgumentNotNull(Object value, String paramName) in ...\Composite\Verify.cs:line 26
   at Composite.C1Console.Security.PermissionTypeFacade.GetCurrentPermissionTypes(UserToken userToken, EntityToken entityToken, IEnumerable`1 userPermissionDefinitions, IEnumerable`1 userGroupPermissionDefinitions) in ...\Composite\C1Console\Security\PermissionTypeFacade.cs:line 92
   at Composite.Data.DynamicTypes.DataTypeDescriptorFormsHelper.GetAvailablePublishingFlowTransitions(EntityToken entityToken) in ...\Composite\Data\DynamicTypes\DataTypeDescriptorFormsHelper.cs:line 272
   at Composite.Data.DynamicTypes.DataTypeDescriptorFormsHelper.GetNewBindings() in ...\Composite\Data\DynamicTypes\DataTypeDescriptorFormsHelper.cs:line 254
   at Composite.Data.DynamicTypes.DataTypeDescriptorFormsHelper.UpdateWithNewBindings(Dictionary`2 bindings) in ...\Composite\Data\DynamicTypes\DataTypeDescriptorFormsHelper.cs:line 201
   at Composite.C1Console.Elements.ElementProviderHelpers.AssociatedDataElementProviderHelper.AddAssociatedDataWorkflow.enterDataCodeActivity_ExecuteCode(Object sender, EventArgs e) in ...\Composite.Workflows\C1Console\Elements\ElementProviderHelpers\AssociatedDataElementProviderHelper\AddAssociatedDataWorkflow.cs:line 139
   at System.Workflow.ComponentModel.Activity.RaiseEvent(DependencyProperty dependencyEvent, Object sender, EventArgs e)
   at System.Workflow.Activities.CodeActivity.Execute(ActivityExecutionContext executionContext)
   at System.Workflow.ComponentModel.ActivityExecutor`1.Execute(T activity, ActivityExecutionContext executionContext)
   at System.Workflow.ComponentModel.ActivityExecutor`1.Execute(Activity activity, ActivityExecutionContext executionContext)
   at System.Workflow.ComponentModel.ActivityExecutorOperation.Run(IWorkflowCoreRuntime workflowCoreRuntime)
   at System.Workflow.Runtime.Scheduler.Run()
System.InvalidOperationException: Error executing workflow f707dbfb-594c-473e-a6f1-24e0b8231d8b 
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId) in ...\Composite\C1Console\Workflow\WorkflowFacadeImpl.cs:line 279
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(WorkflowInstance workflowInstance) in ...\Composite\C1Console\Workflow\WorkflowFacadeImpl.cs:line 288
   at Composite.C1Console.Workflow.WorkflowFacade.RunWorkflow(WorkflowInstance workflowInstance) in ...\Composite\C1Console\Workflow\WorkflowFacade.cs:line 148
   at Composite.C1Console.Workflow.WorkflowActionExecutor.Execute(String serializedEntityToken, String serializedActionToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in ...\Composite\C1Console\Workflow\WorkflowActionExecutor.cs:line 27
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(IActionExecutorSerializedParameters actionExecutor, String serializedEntityToken, String serializedActionToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in ...\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 153
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(EntityToken entityToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer, TaskManagerEvent taskManagerEvent) in ...\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 77
   at Composite.C1Console.Actions.ActionExecutorFacade.Execute(EntityToken entityToken, ActionToken actionToken, FlowControllerServicesContainer flowControllerServicesContainer) in ...\Composite\C1Console\Actions\ActionExecutorFacade.cs:line 25
   at Composite.Core.WebClient.FlowMediators.ActionExecutionMediator.ExecuteElementAction(ElementHandle elementHandle, ActionHandle actionHandle, String consoleId) in ...\Composite\Core\WebClient\FlowMediators\ActionExecutionMediator.cs:line 19

   at Composite.Core.WebClient.FlowMediators.TreeServicesFacade.ExecuteElementAction(String providerName, String serializedEntityToken, String piggybag, String serializedActionToken, String consoleId) in ...\Composite\Core\WebClient\FlowMediators\TreeServicesFacade.cs:line 248
   at Composite.Services.TreeServices.ExecuteSingleElementAction(ClientElement clientElement, String serializedActionToken, String consoleId) in ...\Website\Composite\services\Tree\TreeServices.asmx:line 368

```

**Comment by napernik** [comment]
Fixed here https://github.com/Orckestra/CMS-Foundation/commit/f737d89323f6e3a4072c87c967adfea5d45114d7

**Comment by wwwysocki** [comment]
Verified on https://github.com/Orckestra/CMS-Foundation/releases/tag/v5.4
